"""Added music column to game table

Revision ID: 03d8ec0a2b43
Revises: d6af3300468f
Create Date: 2023-08-08 14:42:30.673318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d8ec0a2b43'
down_revision = 'd6af3300468f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameMusic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('gameMusic')

    # ### end Alembic commands ###
