"""Added music column to game table

Revision ID: d6af3300468f
Revises: 41f9d5a640cc
Create Date: 2023-08-08 14:41:42.090363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6af3300468f'
down_revision = '41f9d5a640cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameMusic', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['gameMusic'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gameMusic')

    # ### end Alembic commands ###
